language: python
python:
  - '3.4'
sudo: false
env:
  global:
    - BUILD_SOC=1
    - secure: "DUk/Ihg8KbbzEgPF0qrHqlxU8e8eET9i/BtzNvFddIGX4HP/P2qz0nk3cVkmjuWhqJXSbC22RdKME9qqPzw6fJwJ6dpJ3OR6dDmSd7rewavq+niwxu52PVa+yK8mL4yf1terM7QQ5tIRf+yUL9qGKrZ2xyvEuRit6d4cFep43Ws="
before_install:
  - mkdir -p $HOME/.mlabs
  - if [ $TRAVIS_PULL_REQUEST != false ]; then BUILD_SOC=0; fi
  - if [ $BUILD_SOC -ne 0 ]; then ./.travis/get-xilinx.sh; fi
  - . ./.travis/get-toolchain.sh
  - . ./.travis/get-anaconda.sh
  - source $HOME/miniconda/bin/activate py34
  - conda install -q pip coverage anaconda-client migen cython
  - pip install coveralls
install:
  - conda build conda/artiq
  - conda install -q artiq --use-local
script:
  - coverage run --source=artiq setup.py test
  - make -C doc/manual html
after_success:
  - anaconda -q login --hostname $(hostname) --username $binstar_login --password $binstar_password
  - anaconda -q upload --user $binstar_login --channel dev --force $HOME/miniconda/conda-bld/linux-64/artiq-*.tar.bz2
  - anaconda -q logout
  - coveralls
notifications:
  email:
    recipients:
      - rjordens@nist.gov
    on_success: always
    on_failure: never
  irc:
    channels:
      - chat.freenode.net#m-labs
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
      - "Build details : %{build_url}"
