package:
    name: llvmlite-or1k
    version: "0.2.1"

source:
    git_url: https://github.com/numba/llvmlite
    git_tag: 11a8303d02e3d6dd2d1e0e9065701795cd8a979f

requirements:
    build:
        - python
        - llvmdev-or1k
        - setuptools
    run:
        - python

build:
    number: 1

test:
    imports:
        - llvmlite_or1k
        - llvmlite_or1k.llvmpy

about:
    home: https://pypi.python.org/pypi/llvmlite/
    license: BSD
