package:
  name: llvmdev-or1k
  version: "3.4"

source:
  git_url: https://github.com/openrisc/llvm-or1k
  git_tag: master

build:
  number: 2

requirements:
  build:
    - system [linux and not armv6]
    - cmake [linux]
  run:
    - system [linux and not armv6]

#test:
#commands:
#- clang --help [linux and not armv6]

about:
  home: http://llvm.org/
  license: Open Source (http://llvm.org/releases/3.4/LICENSE.TXT)
  summary: Development headers and libraries for LLVM
